framework:
    messenger:
        failure_transport: failed
        buses:
            command_bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - dispatch_after_current_bus
                    - doctrine_transaction
                default_middleware: allow_no_handlers

        transports:
            main:
                dsn: 'doctrine://default?queue_name=main'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                options:
                    auto_setup: false

            failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Messenger\Message\PublishArticleMessage': main

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
